### ISSUE TITLE
Missing Unit and tmp workout file

### ISSUE THREAD

**Issue by blcarlson01** [mereldawu/ipyhealth#2]
* ipyhealth version: 0.1.2  
* Python version: 3.7.4
* Operating System: macos 10.15.6

### Description

Installed via Pypi.

I tried to run the sample code again my dataset and got the following errors:
/parser.py", line 137, in format_standard
    raise NotImplementedError("Unit {unit} not implemented.")
NotImplementedError: Unit {unit} not implemented.

and

FileNotFoundError: [Errno 2] No such file or directory: 'apple_health_export/tmp/Workout0.pkl'

I haven't spent any time trying to debug, but wanted to pass the error along in case it was helpful.

**Comment by mereldawu** [comment]
Hi Brandon,

I suspect the issue is because I only implemented conversions for metric systems and not imperial.

For the metric system, the units are km, kcal, and min for distance, energy and duration, respectively. 
Can you help me confirm for the imperial units, it would be mi, kcal, min as below?

| units | distance | energy | duration |
|:----:|:----:|:----|:----:|
|metric| km | kcal | min/sec |
|imperial | mi | kcal | min/sec |

I've already added mi to the function, would you mind testing it for me by installing the package from the issue branch?

```
pip install git+https://github.com/mereldawu/ipyhealth.git@issue-2-Missing_Unit_and_tmp_workout_file
```

Thanks!

**Comment by blcarlson01** [comment]
Hi,

Just tested the change and it worked perfectly!  I was hoping it was something that simple.
